CREATE TABLE rooms (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  room_name VARCHAR(255) NOT NULL,
  is_on TINYINT(1) DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE rooms
ADD FOREIGN KEY (user_id) REFERENCES users(id);
